# Generated by Django 5.1 on 2024-10-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите Email клиента", max_length=254, unique=True, verbose_name="Email клиента"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите Ф. И. О. клиента", max_length=255, verbose_name="Ф. И. О. клиента"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, help_text="Введите коментарий", null=True, verbose_name="Коментарий"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "db_table": "clients",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "theme",
                    models.CharField(
                        help_text="Введите тему сообщения", max_length=255, verbose_name="Тема cообщения"
                    ),
                ),
                (
                    "text_message",
                    models.TextField(help_text="Введите текст сообщения", verbose_name="Текст сообщения"),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "db_table": "messages",
                "ordering": ["theme"],
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "date_first_message",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время первой отправки"),
                ),
                (
                    "date_end_message",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата и время окончания отправки"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("created", "Создана"), ("running", "Запущена"), ("completed", "Завершена")],
                        default="created",
                        max_length=9,
                        verbose_name="Статус",
                    ),
                ),
                ("clients", models.ManyToManyField(related_name="mailing_clients", to="mailing_manager.client")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_message",
                        to="mailing_manager.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "db_table": "mailings",
                "ordering": ["date_first_message"],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_attempt", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("successful", "Успешно"), ("not_successful", "Не успешно")],
                        max_length=14,
                        verbose_name="Статус",
                    ),
                ),
                ("server_response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_attempts",
                        to="mailing_manager.mailing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "db_table": "mailing_attempts",
                "ordering": ["date_attempt"],
            },
        ),
    ]
