# Generated by Django 5.1 on 2024-11-04 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_view_clients", "Может просматривать чужих клиентов")],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["date_first_message"],
                "permissions": [
                    ("can_view_mailing", "Может просматривать чужие рассылки"),
                    ("can_mailing_blocked", "Может блокировать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["theme"],
                "permissions": [("can_view_message", "Может просматривать чужие сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Блокировка"),
        ),
        migrations.AddField(
            model_name="mailing",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attemts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                help_text="Выберете получателей рассылки",
                related_name="mailing_clients",
                to="mailing_manager.client",
                verbose_name="Клиенты",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="date_end_message",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите дату и время окончания отправки",
                null=True,
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="date_first_message",
            field=models.DateTimeField(
                blank=True,
                help_text="Введите дату и время первой отправки",
                null=True,
                verbose_name="Дата и время первой отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.OneToOneField(
                help_text="Выберете связанное сообщение",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_messages",
                to="mailing_manager.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="date_attempt",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки"),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_attempts",
                to="mailing_manager.mailing",
                verbose_name="Рассылка",
            ),
        ),
    ]
