# Generated by Django 5.1 on 2024-11-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_manager", "0002_alter_client_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_view_other_client", "Может просматривать чужих клиентов")],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["date_first_message"],
                "permissions": [
                    ("can_view_other_mailing", "Может просматривать чужие рассылки"),
                    ("can_mailing_blocked", "Может блокировать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["theme"],
                "permissions": [("can_view_other_message", "Может просматривать чужие сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
